version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    ports:
      - 5000:5432
    
    environment:
      POSTGRES_DB: prismadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres